name = "ModifiedHankelFunctionsOfOrderOneThird"
uuid = "b1c65800-dbf0-11e8-0001-4d87e1e07e69"
authors = ["Forrest Gasdia <17058025+fgasdia@users.noreply.github.com>"]
version = "1.1.1"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
SpecialFunctions = "0.10, 1"
StaticArrays = "0.12, 1"
julia = "1.4"
